= Index
Autogenerated index of terms, concepts, functions, and opcodes.

== Opcodes

- `OP_0x`: specifications/vm-core/execution-model
- `OP_0x78`: implementations/zig/zig-cstkptrl-bug-fix
- `OP_1`: specifications/INDEX, specifications/quickstart ...
- `OP_2`: specifications/quickstart
- `OP_6`: specifications/quickstart
- `OP_7`: specifications/quickstart
- `OP_A`: reference/glossary
- `OP_BIGATOMS`: implementations/zig/zig-gvar-bigatoms-implementation
- `OP_Byte`: specifications/instruction-set/instruction-format
- `OP_Categories`: components/vm-core, core/architecture ...
- `OP_Complete`: specifications/instruction-set/execution-semantics
- `OP_Conflicts`: implementations/lisp-implementation, implementations/zig-implementation ...
- `OP_Coverage`: specifications/DOCUMENTATION_REVIEW
- `OP_Decoding`: implementations/zig/zig-opcode-findings
- `OP_Deep`: implementations/c/c-emulator-copy-tracing, implementations/c/c-emulator-getbaseptr-tracing ...
- `OP_Detailed`: implementations/c/c-emulator-address-xor-tracing, implementations/c/c-emulator-copy-tracing ...
- `OP_Details`: implementations/c/c-emulator-const1-tracing, implementations/c/c-emulator-eq-tracing ...
- `OP_Dispatch`: core/architecture
- `OP_Documentation`: core/contributing, specifications/CONTRIBUTING
- `OP_Execution`: specifications/instruction-set/execution-semantics, specifications/validation/reference-behaviors
- `OP_Findings`: implementations/zig/zig-opcode-findings
- `OP_Gaps`: implementations/zig/zig-opcode-findings
- `OP_Handler`: components/vm-core, specifications/instruction-set/execution-semantics
- `OP_Handlers`: components/vm-core, core/architecture ...
- `OP_Handling`: implementations/zig-implementation, specifications/vm-core/execution-model
- `OP_Implementation`: implementations/lisp-implementation, implementations/zig/zig-implementation-findings ...
- `OP_Implementations`: specifications/SOURCE_CODE_MAPPING, specifications/SOURCE_CODE_MAPPING-VM-Core
- `OP_Implemented`: implementations/lisp-implementation
- `OP_Length`: specifications/instruction-set/instruction-format, specifications/instruction-set/opcodes-reference
- `OP_Mapping`: implementations/c/c-emulator-tjump1-tracing
- `OP_N`: specifications/instruction-set/README, specifications/instruction-set/opcodes ...
- `OP_Name`: implementations/c/c-emulator-const1-tracing, implementations/c/c-emulator-eq-tracing ...
- `OP_Organization`: specifications/instruction-set/README
- `OP_PC`: implementations/c/c-emulator-pc-advancement-fix
- `OP_Placeholders`: implementations/zig-implementation
- `OP_Reference`: implementations/zig/zig-opcode-findings, specifications/INDEX ...
- `OP_Review`: implementations/zig/zig-implementation-execution-debugging
- `OP_SOMETHING`: CRITICAL_DEBUGGING_TECHNIQUE
- `OP_Semantics`: specifications/INDEX
- `OP_Some`: specifications/instruction-set/instruction-format
- `OP_TOS_1`: implementations/c/c-emulator-eq-tracing, specifications/vm-core/stack-management
- `OP_Table`: specifications/instruction-set/execution-semantics
- `OP_Test`: specifications/validation/reference-behaviors
- `OP_Tests`: specifications/validation/README
- `OP_Tracing`: implementations/README, implementations/c/c-emulator-const1-tracing ...
- `OP_advance`: implementations/c/c-emulator-pc-advancement-fix
- `OP_analysis`: implementations/c/c-emulator-copy-tracing, implementations/c/c-emulator-getbaseptr-tracing ...
- `OP_and`: CRITICAL_DEBUGGING_TECHNIQUE, implementations/zig/zig-implementation-xor-addressing ...
- `OP_are`: implementations/zig/zig-opcode-findings, specifications/DOCUMENTATION_REVIEW ...
- `OP_aref1`: specifications/instruction-set/opcodes-data
- `OP_as`: implementations/zig/zig-opcode-findings
- `OP_aset1`: specifications/instruction-set/opcodes-data
- `OP_assoc`: specifications/instruction-set/opcodes-data
- `OP_at`: implementations/c/c-emulator-address-xor-tracing, implementations/c/c-emulator-myargcount-tracing
- `OP_blt`: specifications/SOURCE_CODE_MAPPING, specifications/SOURCE_CODE_MAPPING-Display-IO
- `OP_boxidiff`: specifications/instruction-set/opcodes-arithmetic
- `OP_boxiplus`: specifications/instruction-set/opcodes-arithmetic
- `OP_byte`: implementations/c/c-emulator-address-xor-tracing, implementations/c/c-emulator-fjump7-tracing ...
- `OP_category`: specifications/instruction-set/instruction-format
- `OP_commented`: core/contributing, implementations/zig/zig-opcode-findings
- `OP_conflicts`: implementations/zig/zig-implementation-findings, implementations/zig/zig-opcode-findings
- `OP_cons`: specifications/SOURCE_CODE_MAPPING, specifications/SOURCE_CODE_MAPPING-Memory
- `OP_contextsw`: specifications/SOURCE_CODE_MAPPING, specifications/SOURCE_CODE_MAPPING-VM-Core
- `OP_correctly`: specifications/platform-abstraction/implementation-choices
- `OP_coverage`: specifications/COMPLETENESS, specifications/DOCUMENTATION_REVIEW ...
- `OP_decoding`: implementations/zig/zig-opcode-findings, specifications/instruction-set/opcodes-reference
- `OP_defined`: implementations/zig-implementation
- `OP_definitions`: components/vm-core, implementations/lisp-implementation
- `OP_details`: implementations/zig/zig-implementation-findings-opcodes
- `OP_do`: implementations/zig-implementation, specifications/instruction-set/opcodes-reference
- `OP_documented`: specifications/COMPLETENESS
- `OP_during`: implementations/zig-implementation
- `OP_enumeration`: implementations/README, implementations/zig-implementation ...
- `OP_execute`: implementations/zig/zig-cstkptrl-bug-fix
- `OP_executes`: implementations/c/c-emulator-pc-advancement-fix
- `OP_execution`: implementations/c/c-emulator-const1-tracing, implementations/c/c-emulator-eq-tracing ...
- `OP_exist`: core/contributing, specifications/instruction-set/opcodes-reference
- `OP_exists`: specifications/instruction-set/opcodes-reference
- `OP_findings`: implementations/README
- `OP_fmemb`: specifications/instruction-set/opcodes-data
- `OP_for`: core/architecture, implementations/zig-implementation ...
- `OP_from`: implementations/zig/zig-opcode-findings
- `OP_gcref`: components/memory-management, reference/api ...
- `OP_grouped`: specifications/instruction-set/README
- `OP_gvarset`: specifications/instruction-set/opcodes-control-memory
- `OP_had`: implementations/zig/zig-opcode-findings
- `OP_handler`: components/memory-management, specifications/SOURCE_CODE_MAPPING ...
- `OP_handlers`: implementations/c/c-emulator-refactoring, implementations/lisp-implementation ...
- `OP_handling`: implementations/zig-implementation
- `OP_have`: implementations/zig/zig-opcode-findings, specifications/instruction-set/instruction-format
- `OP_identically`: specifications/platform-abstraction/implementation-choices
- `OP_idifferencen`: specifications/instruction-set/opcodes-arithmetic
- `OP_if`: specifications/vm-core/execution-model
- `OP_implementation`: implementations/c/execution-comparison-results, implementations/zig-implementation ...
- `OP_implementations`: CRITICAL_DEBUGGING_TECHNIQUE, implementations/zig-implementation ...
- `OP_implemented`: core/introduction, core/readme ...
- `OP_in`: CRITICAL_DEBUGGING_TECHNIQUE, implementations/zig/zig-implementation-findings-sysout ...
- `OP_incrementally`: specifications/quickstart
- `OP_index`: specifications/instruction-set/opcodes-arithmetic, specifications/instruction-set/opcodes-control-memory ...
- `OP_iplusn`: specifications/instruction-set/opcodes-arithmetic
- `OP_iteration`: CRITICAL_DEBUGGING_TECHNIQUE
- `OP_list`: specifications/instruction-set/execution-semantics, specifications/instruction-set/instruction-format ...
- `OP_listget`: specifications/instruction-set/opcodes-data
- `OP_may`: CRITICAL_DEBUGGING_TECHNIQUE, specifications/vm-core/execution-model
- `OP_metadata`: specifications/vm-core/execution-model
- `OP_modify`: implementations/zig/zig-cstkptrl-bug-fix
- `OP_must`: specifications/validation/compatibility-criteria
- `OP_name`: implementations/c/c-emulator-myargcount-tracing, specifications/instruction-set/opcodes-reference ...
- `OP_names`: specifications/vm-core/execution-trace
- `OP_naming`: implementations/zig/zig-opcode-findings
- `OP_need`: implementations/zig-implementation
- `OP_not`: implementations/lisp-implementation, specifications/vm-core/execution-model
- `OP_now`: implementations/zig/zig-implementation-findings-opcodes
- `OP_only`: implementations/c/c-emulator-copy-tracing, specifications/instruction-set/README ...
- `OP_or`: specifications/validation/README
- `OP_organization`: specifications/COMPLETENESS
- `OP_parity`: CRITICAL_DEBUGGING_TECHNIQUE
- `OP_pattern`: CRITICAL_DEBUGGING_TECHNIQUE
- `OP_pilotbitblt`: specifications/DOCUMENTATION_REVIEW, specifications/SOURCE_CODE_MAPPING ...
- `OP_produces`: specifications/quickstart
- `OP_reference`: specifications/COMPLETENESS
- `OP_removed`: implementations/zig-implementation
- `OP_restlist`: specifications/instruction-set/opcodes-data
- `OP_rplcons`: specifications/instruction-set/opcodes-data
- `OP_rplptr`: specifications/instruction-set/opcodes-data
- `OP_sequences`: implementations/zig/zig-implementation-memory-debugging-systematic
- `OP_sequencing`: implementations/zig/zig-cstkptrl-bug-fix
- `OP_span`: components/vm-core, specifications/instruction-set/instruction-format
- `OP_specification`: specifications/CONTRIBUTING, specifications/INDEX
- `OP_specifications`: implementations/lisp-implementation, specifications/SOURCE_CODE_MAPPING-VM-Core ...
- `OP_table`: components/vm-core, implementations/c/c-emulator-const1-tracing ...
- `OP_test`: specifications/validation/compatibility-criteria
- `OP_that`: CRITICAL_DEBUGGING_TECHNIQUE, implementations/zig-implementation ...
- `OP_themselves`: specifications/instruction-set/opcodes-reference
- `OP_to`: implementations/c/c-emulator-copy-tracing, implementations/c/c-emulator-getbaseptr-tracing ...
- `OP_tracing`: implementations/c/c-emulator-myargcount-tracing, implementations/c/c-emulator-refactoring
- `OP_trigger`: specifications/instruction-set/opcodes-reference
- `OP_type`: specifications/instruction-set/instruction-format, specifications/vm-core/execution-model
- `OP_use`: specifications/instruction-set/instruction-format
- `OP_value`: implementations/zig/zig-opcode-findings, specifications/instruction-set/execution-semantics ...
- `OP_values`: implementations/lisp-implementation, implementations/zig/zig-opcode-findings ...
- `OP_variant`: implementations/c/c-emulator-tjump1-tracing
- `OP_variants`: implementations/zig/zig-implementation-execution-debugging
- `OP_was`: implementations/zig/zig-gvar-bigatoms-implementation
- `OP_were`: implementations/zig/zig-opcode-findings
- `OP_while`: specifications/vm-core/execution-model
- `OP_with`: implementations/zig/zig-opcode-findings, specifications/README ...
- `OP_would`: implementations/zig/zig-cstkptrl-bug-fix

== Concepts

- *"$@"*: medley/components/scripts
- *"${maiko}" "${src_sysout}" \*: medley/components/scripts
- *"/file/test.lisp"*: specifications/validation/reference-behaviors
- *"DSK:>file>test.lisp"*: specifications/validation/reference-behaviors
- *# Automatically uses LOGINDIR/INIT.LISP if present*: medley/components/greetfiles
- *# Create LOGINDIR/INIT.LISP*: medley/components/greetfiles
- *# Explicitly continue from vmem (if present*: medley/components/vmem
- *# Ignore config files, use only command-line arguments*: medley/components/configuration
- *# Ignores config file, uses only command-line arguments*: medley/components/configuration
- *# Loads LOGINDIR/vmem/lisp.virtualmem if present*: medley/components/vmem
- *# Loads vmem file if present, otherwise defaults to full.sysout*: medley/components/sysout
- *# Otherwise starts from full.sysout*: medley/components/vmem
- *# Overrides -f from config, uses lisp.sysout instead*: medley/components/configuration
- *# Runs stage 7, creates fuller.database from existing full.sysout*: medley/components/loadup
- *# Runs stages 1-4 and 6, creates lisp.sysout and full.sysout*: medley/components/loadup
- *# Runs stages 1-4, creates full.sysout (not copied to loadups*: medley/components/loadup
- *# Runs stages 1-5 and 6, creates lisp.sysout, full.sysout, and apps.sysout*: medley/components/loadup
- *# Start from full.sysout, ignore vmem file*: medley/components/vmem
- *# Start without REM.CM file*: medley/components/greetfiles
- *# Start without greet file*: medley/components/greetfiles
- *# Use specified vmem file*: medley/components/vmem
- *# Uses ./tmp as work directory*: medley/components/loadup
- *# Uses full.sysout, 1024x768 geometry, run ID "work"*: medley/components/configuration
- *# Uses specified config file*: medley/components/configuration
- *# or*: medley/components/sysout, medley/components/vmem
- *## Code Changes Summary

### Fixed IFPAGE Reading

**File**:*: implementations/zig/zig-enhanced-tracing-status
- *## Comparison with C Emulator

### Expected Matches

1. **FPtoVP Table**: File page 5178 → Virtual page 6204
2. **PC Calculation**: FuncObj = FX_FNHEADER * 2, PC = FuncObj + CURRENTFX->pc
3. **Memory Loading**: Bytes at PC location after byte-swap
4. **Frame Structure**: FX_FNHEADER and CURRENTFX->pc values

### Known Differences

- **Memory Layout**: Absolute addresses differ due to ASLR, but relative calculations should match
- **Byte-Swapping**: Should match C emulator's ntohl() behavior

## Testing

To test enhanced tracing:*: implementations/zig/zig-enhanced-tracing-implementation
- *## Enhanced Tracing Implementation

### Code Added

1. ***: implementations/c/c-emulator-complete-verification
- *## Expected Output Sections

### FPtoVP Table Loading*: implementations/zig/zig-enhanced-tracing-testing
- *## Key Insights

1. **DLword vs Byte Offsets**: Critical distinction - LispPTR is DLword offset, multiply by 2
2. **Two-Level Byte-Swapping**: Both FPtoVP table and page content are swapped
3. **Partial Swapping**: Only first half of FPtoVP table is swapped
4. **Consistency**: All calculations verified and consistent
5. **Mystery**: Execution byte mismatch doesn't affect core logic understanding

## Status Summary

| Component | Status | Verification |
|-----------|--------|--------------|
| Memory Loading | ✅ VERIFIED | FPtoVP mapping, page loading verified |
| Address Conversion | ✅ VERIFIED | DLword → byte offset verified |
| PC Calculation | ✅ VERIFIED | All calculations match execution log |
| Byte-Swapping | ✅ VERIFIED | FPtoVP and page content verified |
| Execution Bytes | ⚠️ MISMATCH | Mystery remains, doesn't affect logic |

## Related Documentation

- [Memory Loading Analysis](c-emulator-memory-loading-analysis.typ)
- [PC Calculation Logic](c-emulator-pc-calculation.typ)
- [Byte-Swapping Logic](c-emulator-byte-swapping.typ)
- [Execution Byte Mismatch](c-emulator-execution-byte-mismatch.typ)

## References

-*: implementations/c/c-emulator-complete-analysis
- *## Next Steps

1. **Build C Emulator**: Ensure*: implementations/c/c-emulator-myargcount-tracing
- *## Step-by-Step Calculation

### 1. FX_FNHEADER

Read from the current frame:

**BIGVM**:*: implementations/c/c-emulator-pc-calculation
- *## Testing Instructions

### 1. Rebuild Zig Emulator*: implementations/zig/zig-enhanced-tracing-testing
- *## Verification Checklist

- [ ] Binary rebuilt successfully
- [ ] Enhanced tracing output captured
- [ ] FX_FNHEADER matches C emulator (*: implementations/zig/zig-enhanced-tracing-testing
- *## Verification Checklist

After rebuild and run:

- [ ] Binary rebuilds without errors
- [ ] No assertion failures
- [ ] Enhanced tracing output appears
- [ ] FX_FNHEADER = 0x307864
- [ ] CURRENTFX->pc = 104
- [ ] FuncObj = 0x60f0c8
- [ ] PC = 0x60f130
- [ ] All calculations match C emulator

## References

- Implementation:*: implementations/zig/zig-enhanced-tracing-status
- *## Verification Status

| Component | Status | Evidence |
|-----------|--------|----------|
| Memory Loading | ✅ VERIFIED | Enhanced trace + sysout analysis |
| Address Conversion | ✅ VERIFIED | Enhanced trace + code analysis |
| PC Calculation | ✅ VERIFIED | Enhanced trace values match calculations |
| Byte-Swapping | ✅ VERIFIED | Enhanced trace shows correct swapping |
| Frame Structure | ✅ VERIFIED | Enhanced trace shows correct fields |

## Documentation

All analysis has been documented in:

1. [Memory Loading Analysis](c-emulator-memory-loading-analysis.typ)
2. [PC Calculation Logic](c-emulator-pc-calculation.typ)
3. [Byte-Swapping Logic](c-emulator-byte-swapping.typ)
4. [Execution Byte Mismatch](c-emulator-execution-byte-mismatch.typ)
5. [Enhanced Tracing Results](c-emulator-enhanced-tracing-results.typ)
6. [Complete Analysis](c-emulator-complete-analysis.typ)

## Conclusion

✅ **All C emulator logic fully verified and consistent**

Enhanced tracing successfully captured runtime values that confirm:
- Memory loading algorithm is correct
- Address conversion logic is correct
- PC calculation logic is correct
- Byte-swapping logic is correct

The execution byte mismatch from the previous log remains unexplained but does not affect understanding of the core algorithms.

**Status**: ✅ **VERIFICATION COMPLETE**

## References

- Enhanced trace:*: implementations/c/c-emulator-complete-verification
- *## Verified Values (from Execution Log)

From execution log analysis:

- **PC byte offset**:*: implementations/c/c-emulator-pc-calculation
- *## Virtual Page Calculation

- **PC virtual page**:*: implementations/c/c-emulator-pc-calculation
- *## Zig Implementation

**Location**:*: implementations/c/c-emulator-myargcount-tracing
- *### 2. Address Conversion ✅ VERIFIED

**Source**: Enhanced trace output + code analysis

**Verified**:
- ✅*: implementations/c/c-emulator-complete-verification
- *### 2. Run with Enhanced Tracing*: implementations/zig/zig-enhanced-tracing-testing
- *### 3. Extract Key Values*: implementations/zig/zig-enhanced-tracing-testing
- *### 3. PC Calculation ✅ VERIFIED

**Source**: Enhanced trace output

**Captured Values**:
- FX_FNHEADER:*: implementations/c/c-emulator-complete-verification
- *### 4. Compare with C Emulator

Compare*: implementations/zig/zig-enhanced-tracing-testing
- *### Algorithm

1. **Check Condition**: If*: implementations/c/c-emulator-fjump7-tracing
- *### Algorithm

1. **Compare**: Check if*: implementations/c/c-emulator-eq-tracing
- *### Algorithm

1. **Determine Frame Type**: Check*: implementations/c/c-emulator-myargcount-tracing
- *### Algorithm

1. **Push Constant**:*: implementations/c/c-emulator-const1-tracing
- *### FJUMPMACRO Definition*: implementations/c/c-emulator-fjump7-tracing
- *### FastRetCALL Tracing*: implementations/zig/zig-enhanced-tracing-implementation, implementations/zig/zig-enhanced-tracing-testing
- *### First Instruction Tracing*: implementations/zig/zig-enhanced-tracing-implementation, implementations/zig/zig-enhanced-tracing-testing
- *### How ntohl() Works*: implementations/c/c-emulator-byte-swapping
- *### Instruction #12 Tracer

**Location**:*: implementations/c/c-emulator-myargcount-tracing
- *### NativeAligned4FromLAddr*: implementations/c/c-emulator-memory-loading-analysis
- *### PC Calculation*: implementations/c/c-emulator-complete-analysis
- *### PC Calculation Flow*: implementations/c/c-emulator-complete-verification
- *### Swap Boundary

- **Boundary**: First*: implementations/c/c-emulator-byte-swapping
- *### Swap Logic

Each page is 512 bytes = 128 DLwords = 64 longwords (32-bit)

**32-bit longword swap**:*: implementations/c/c-emulator-byte-swapping
- *### Verification

✅ **Logic Match**: Zig implementation matches C logic exactly:
- Frame type detection (alink & 1)
- Normal frame:*: implementations/c/c-emulator-myargcount-tracing
- *### Verified Example

**File page 5178, PC offset 0x98**:
- Raw bytes:*: implementations/c/c-emulator-byte-swapping
- *### Verified Mapping

- **File page 5178** → **Virtual page 6204** (confirmed, only mapping)
- PC location: Virtual page 6204, offset 0x98 (152 bytes)

## Page Content Byte-Swapping

Each page (512 bytes) is byte-swapped using 32-bit longword swap:*: implementations/c/c-emulator-memory-loading-analysis
- *### word_swap_page Function*: implementations/c/c-emulator-byte-swapping
- *#define GETFPTOVP(b, o*: specifications/data-structures/sysout-format-fptovp
- *#define GETPAGEOK(b, o) ((b)[o] >> 16)     // Returns high 16 bits (page OK flag)*: specifications/data-structures/sysout-format-fptovp
- *#ifdef*: core/architecture
- *#ifdef BYTESWAP*: specifications/data-structures/sysout-byte-swapping, specifications/data-structures/sysout-format ...
- *#include "xc_tracing.h"*: implementations/c/c-emulator-refactoring
- *$HOME*: medley/platform/linux, medley/platform/macos
- *${borderwidth_flag} ${borderwidth_value} \*: medley/components/scripts
- *${mem_flag} ${mem_value} \*: medley/components/scripts
- *${nh_debug_flag} ${nh_debug_value} \*: medley/components/scripts
- *${nh_host_flag} ${nh_host_value} \*: medley/components/scripts
- *${nh_mac_flag} ${nh_mac_value} \*: medley/components/scripts
- *${nh_port_flag} ${nh_port_value} \*: medley/components/scripts
- *${nofork_arg} \*: medley/components/scripts
- *${noscroll_arg} \*: medley/components/scripts
- *${pixelscale_flag} ${pixelscale_value} \*: medley/components/scripts
- *%-16s*: specifications/vm-core/trace-and-logging-formats
- *%-20s*: specifications/vm-core/trace-and-logging-formats
- *%-30s*: specifications/vm-core/trace-and-logging-formats
- *%-40s*: specifications/vm-core/execution-trace
- *%02x%02x%02x%02x%02x%02x%02x%02x*: specifications/vm-core/execution-trace
- *%5d*: specifications/vm-core/execution-trace
- *%5d PC: 0x%06x (Lisp_world+0x%06x, FuncObj+%5d bytes) %16s %-40s Stack: D:%5d P:%5d TOS:0x%016lx N:[...] Frame: FX:%5d FH:0x%06x PC:%5d NB:%5d FO:+%5d*: implementations/c/c-emulator-enhanced-tracing-proposal
- *%6d*: specifications/vm-core/trace-and-logging-formats
- *%USERPROFILE%\AppData\Local\Interlisp\vncviewer.exe*: medley/platform/wsl
- *& 0x7ff*: specifications/vm-core/type-checking
- *& 0xFF*: implementations/zig-implementation
- *((5 * index) + 2) * sizeof(LispPTR)*: specifications/data-structures/atom-table
- *((~(n1 + n2)) << 16) | (offset << 1)*: specifications/instruction-set/opcodes-control-memory
- *(0x00000000, represents NIL/false)
4. **Stack Effect**: Both TOS and POP_TOS_1 are consumed (stack depth decreases by 1)
5. **PC Advancement**: PC advances by 1 byte (*: implementations/c/c-emulator-eq-tracing
- *(0x0000012e >> 16)*: specifications/data-structures/sysout-format, specifications/data-structures/sysout-format-fptovp
- *(0x30 << 16) | 0x7864 = 0x307864*: implementations/zig/zig-implementation-findings-vm
- *(0x30 ^ 3 = 0x33)
-*: implementations/c/c-emulator-address-xor-tracing
- *(0x31 ^ 3 = 0x32)
-*: implementations/c/c-emulator-address-xor-tracing
- *(0x32 ^ 3 = 0x31)
   - Reads from:*: implementations/c/c-emulator-address-xor-tracing
- *(0x32 ^ 3 = 0x31)
-*: implementations/c/c-emulator-address-xor-tracing
- *(0x33 ^ 3 = 0x30)

This swaps bytes within 4-byte boundaries, compensating for byte-swapped memory layout after 32-bit longword swapping during page load.

=== Get_Pointer for BIGVM

*Location*:*: implementations/c/c-emulator-address-xor-tracing
- *(0x33 ^ 3 = 0x30)
   - Reads from:*: implementations/c/c-emulator-address-xor-tracing
- *(0x34 ^ 3 = 0x37)
   - Reads from:*: implementations/c/c-emulator-address-xor-tracing
- *(0x35 ^ 3 = 0x36)
   - Reads from:*: implementations/c/c-emulator-address-xor-tracing
- *(0x4c, represents T/true)
3. **If Not Equal**: Set*: implementations/c/c-emulator-eq-tracing
- *(0x60f132) XOR 3 → 0x60f131 (reads from PC+0)
-*: implementations/c/c-emulator-address-xor-tracing
- *(0x60f132) XOR 3 → 0x60f131: reads from different 4-byte boundary
- This effectively reconstructs the original big-endian value

**Result**:*: implementations/c/c-emulator-address-xor-tracing
- *(0x60f133) XOR 3 → 0x60f130 (reads from PC-1)
-*: implementations/c/c-emulator-address-xor-tracing
- *(0x60f134) XOR 3 → 0x60f137 (reads from PC+7)
-*: implementations/c/c-emulator-address-xor-tracing
- *(0x60f135) XOR 3 → 0x60f136 (reads from PC+6)

This suggests the memory was loaded with 32-bit longword byte-swapping, and XOR addressing reverses this swap to read the correct byte order.

=== Understanding the Byte-Swap Pattern

**Memory Loading Process**:
1. Sysout file contains big-endian data:*: implementations/c/c-emulator-address-xor-tracing
- *(1 variable)
-*: implementations/c/c-emulator-unbind-tracing
- *(104 bytes) ✓

## Enhanced Tracing Code Status

Enhanced tracing code was added to:
-*: implementations/c/c-emulator-enhanced-tracing-results
- *(16-bit word pointer)
-*: implementations/c/c-emulator-pc-calculation
- *(161 decimal,*: implementations/c/c-emulator-tjump1-tracing
- *(2 DLwords)

**Interpretation**:
- Will unbind **1 variable**
- Starting from PVAR offset **2 DLwords**

=== PVAR Calculation

**PVAR**:*: implementations/c/c-emulator-unbind-tracing
- *(2-byte values). The*: implementations/zig/zig-cstkptrl-bug-fix
- *(24-bit, masked to 0xFFFFFF)

This matches the frame reading logic in*: implementations/zig/zig-frame-initialization-analysis
- *(3 bytes).

So the actual behavior is:
-*: implementations/c/c-emulator-address-xor-tracing
- *(3.3). Low risk, high clarity.
- *Phase 2*: Move implementation-independent specs (3.2), consolidate glossary/index (3.3), and extend*: DOCUMENTATION_IMPROVEMENT_PROPOSAL
- *(5 * 10) + 2 = 52*: specifications/data-structures/atom-table
- *(5 * index) + 2*: specifications/data-structures/atom-table
- *(522 decimal)
- **Status**: ✅ **SUCCESS: GVAR operand extraction matches C emulator**

=== Conclusion

The Zig emulator's XOR addressing implementation correctly matches the C emulator:
1. ✅ Memory loading with byte-swapping produces identical content
2. ✅ XOR addressing reads from correct locations
3. ✅ 4-byte pointer operand extraction works correctly
4. ✅ GVAR atom_index calculation matches C emulator

== Next Steps

1. ✅ Add comprehensive tracing to C emulator
2. ✅ Execute and capture trace output
3. ✅ Analyze trace to understand address/XOR mechanism
4. ✅ Document findings in this file
5. ✅ Update Zig implementation to match C behavior
6. ✅ Verify XOR addressing matches between C and Zig emulators
7. ⏳ Continue with execution log comparison to verify full execution path

== Related Documentation

-*: implementations/c/c-emulator-address-xor-tracing
- *(54 decimal)
- This is the byte offset from the base pointer

=== Stack State Before GETBASEPTR_N

- **TopOfStack (TOS)**:*: implementations/c/c-emulator-getbaseptr-tracing
- *(54)
- **target_addr = base_ptr + operand_byte**:*: implementations/c/c-emulator-getbaseptr-tracing
- *(A . B)*: specifications/validation/reference-behaviors
- *(BIGVM, incomplete!)
- Page loading: 32-bit longword swapping
- First half of FPtoVP swapped, second half NOT swapped (incomplete implementation!)

=== Technique 7: Offset Verification

*Purpose*: Verify offsets are calculated correctly

*Method*:
1. Calculate offset using formula
2. Verify offset is within bounds
3. Check if offset matches expected value
4. Apply critical debugging technique: offset, offset/2, offset*2

*Common Offset Issues*:
- Byte vs DLword confusion (factor of 2)
- Base address wrong (add/subtract error)
- Alignment issues (not multiple of 2 or 4)

== Systematic Investigation Plan

=== Phase 1: PC Address Verification

*Goal*: Verify PC 0x307898 is correct

*Steps*:
1. ✅ Verify PC initialization sets PC to 0x307898
2. ⏳ Verify PC 0x307898 is valid address
3. ⏳ Calculate virtual page:*: implementations/zig/zig-implementation-memory-debugging-systematic
- *(BYTESPER_PAGE)
- File page lookup:*: implementations/zig/zig-implementation-memory-debugging-systematic
- *(CurrentStackPTR - Stackspace) / 2*: implementations/zig-implementation, implementations/zig/zig-implementation-execution-debugging ...
- *(DLword *)IVAR + x*: specifications/instruction-set/opcodes-control-memory
- *(DLword *)PVAR + ...*: implementations/c/execution-comparison-results
- *(DLword *)PVAR + x*: specifications/instruction-set/opcodes-control-memory
- *(DLword offset)
-*: implementations/c/c-emulator-memory-loading-analysis
- *(FastRetCALL)
- C frame struct:*: implementations/zig/zig-frame-initialization-analysis
- *(FuncObj / 2)
- **CURRENTFX->pc**:*: implementations/c/c-emulator-pc-calculation
- *(INVALID - 0xFFFF values)

**Problem**: Zig is reading invalid frame values (0xFFFF), indicating:
1. Frame is not being read correctly, OR
2. Frame is uninitialized/sparse, OR
3. Frame offset calculation is wrong

== Findings

=== Issue 1: Frame Reading

The Zig debug output shows:*: implementations/zig/zig-frame-initialization-analysis
- *(IVar base address)
   -*: implementations/c/c-emulator-myargcount-tracing
- *(LCP,*: CRITICAL_DEBUGGING_TECHNIQUE
- *(LispPTR *)AtomSpace + offset*: specifications/data-structures/atom-table
- *(Lisp_world+0x60f130)
- Frame:*: implementations/zig/zig-frame-initialization-analysis
- *(PC + 1)
- **PCMAC**:*: implementations/c/c-emulator-address-xor-tracing
- *(PC - 104)
- **FX_FNHEADER DLword offset**:*: implementations/c/c-emulator-pc-calculation
- *(PCMAC) ^ 3*: implementations/zig/zig-implementation-xor-addressing
- *(POINTERMASK & a) < (POINTERMASK & b)*: specifications/instruction-set/opcodes-arithmetic
- *(POINTERMASK & base) + byteoffset*: specifications/instruction-set/opcodes-arithmetic
- *(POINTERMASK & base) + index*: specifications/instruction-set/opcodes-arithmetic
- *(POINTERMASK & base) + offset*: specifications/instruction-set/opcodes-arithmetic
- *(SETQ INTERLISPMODE T*: medley/components/greetfiles
- *(WRONG!)
- Frame shows:*: implementations/zig/zig-frame-initialization-analysis
- *(XOR addressed) → high byte (<<16)
- Byte at*: implementations/zig/zig-gvar-bigatoms-implementation
- *(XOR addressed) → low byte
- Byte at*: implementations/zig/zig-gvar-bigatoms-implementation
- *(XOR addressed) → middle byte (<<8)

Since*: implementations/zig/zig-gvar-bigatoms-implementation
- *(add address trace)

=== Phase 4: FPtoVP Lookup Trace

*Tasks*:
1. Add FPtoVP lookup trace log
2. Implement lookup function with tracing
3. Log search process
4. Log final mapping

*Files*:
-*: implementations/c/c-emulator-enhanced-tracing-proposal
- *(add jump offset, where x=3 for TJUMP1)
   -*: implementations/c/c-emulator-tjump1-tracing

