(in-package :maiko-lisp.vm)

;; Opcode dispatch table and handler registration
;; This file provides the unified interface to all opcode handlers

;; Note: *opcode-handlers* and register-opcode-handler are defined in dispatch.lisp

;; Initialize all opcode handlers
(defun initialize-opcode-handlers ()
  "Initialize all opcode handlers by registering them"
  (clrhash *opcode-handlers*)
  ;; Note: initialize-byte-opcode-map is called at the end of dispatch.lisp
  ;; to ensure proper load order regardless of file loading sequence

  ;; Stack operations
  (register-opcode-handler 'nil #'handle-nil)
  (register-opcode-handler 't #'handle-t)
  (register-opcode-handler 'pop #'handle-pop)
  (register-opcode-handler 'push #'handle-push)
  (register-opcode-handler 'const-0 #'handle-const-0)
  (register-opcode-handler 'const-1 #'handle-const-1)
  (register-opcode-handler 'copy #'handle-copy)

  ;; Arithmetic operations
  (register-opcode-handler 'iplus2 #'handle-iplus2)
  (register-opcode-handler 'idifference #'handle-idifference)
  (register-opcode-handler 'itimes2 #'handle-itimes2)
  (register-opcode-handler 'iquo #'handle-iquo)
  (register-opcode-handler 'irem #'handle-irem)
  (register-opcode-handler 'iminus #'handle-iminus)
  (register-opcode-handler 'idivide #'handle-idivide)
  (register-opcode-handler 'imod #'handle-imod)

  ;; List operations
  (register-opcode-handler 'car #'handle-car)
  (register-opcode-handler 'cdr #'handle-cdr)
  (register-opcode-handler 'cons #'handle-cons)
  (register-opcode-handler 'rplaca #'handle-rplaca)
  (register-opcode-handler 'rplacd #'handle-rplacd)
  (register-opcode-handler 'createcell #'handle-createcell)
  (register-opcode-handler 'rplcons #'handle-rplcons)
  (register-opcode-handler 'nth #'handle-nth)
  (register-opcode-handler 'nthcdr #'handle-nthcdr)
  (register-opcode-handler 'last #'handle-last)
  (register-opcode-handler 'listlength #'handle-list-length)
  (register-opcode-handler 'append #'handle-append)
  (register-opcode-handler 'reverse #'handle-reverse)

  ;; Comparison operations
  (register-opcode-handler 'eq #'handle-eq)
  (register-opcode-handler 'eql #'handle-eql)
  (register-opcode-handler 'lessp #'handle-lessp)
  (register-opcode-handler 'greaterp #'handle-greaterp)
  (register-opcode-handler 'leq #'handle-leq)
  (register-opcode-handler 'geq #'handle-geq)
  (register-opcode-handler 'equal #'handle-equal)
  (register-opcode-handler 'numequal #'handle-numequal)
  (register-opcode-handler 'igreaterp #'handle-igreaterp)
  (register-opcode-handler 'eq-alt #'handle-eq-alt)
  (register-opcode-handler 'greaterp-alt #'handle-greaterp-alt)
  (register-opcode-handler 'equal-alt #'handle-equal-alt)

  ;; Variable access
  (register-opcode-handler 'ivar0 #'handle-ivar0)
  (register-opcode-handler 'ivar1 #'handle-ivar1)
  (register-opcode-handler 'ivar2 #'handle-ivar2)
  (register-opcode-handler 'ivar3 #'handle-ivar3)
  (register-opcode-handler 'ivar4 #'handle-ivar4)
  (register-opcode-handler 'ivar5 #'handle-ivar5)
  (register-opcode-handler 'ivar6 #'handle-ivar6)
  (register-opcode-handler 'pvar0 #'handle-pvar0)
  (register-opcode-handler 'pvar1 #'handle-pvar1)
  (register-opcode-handler 'pvar2 #'handle-pvar2)
  (register-opcode-handler 'pvar3 #'handle-pvar3)
  (register-opcode-handler 'pvar4 #'handle-pvar4)
  (register-opcode-handler 'pvar5 #'handle-pvar5)
  (register-opcode-handler 'pvar6 #'handle-pvar6)
  (register-opcode-handler 'fvar0 #'handle-fvar0)
  (register-opcode-handler 'fvar1 #'handle-fvar1)
  (register-opcode-handler 'fvar2 #'handle-fvar2)
  (register-opcode-handler 'fvar3 #'handle-fvar3)
  (register-opcode-handler 'fvar4 #'handle-fvar4)
  (register-opcode-handler 'fvar5 #'handle-fvar5)
  (register-opcode-handler 'fvar6 #'handle-fvar6)
  (register-opcode-handler 'gvar #'handle-gvar)
  (register-opcode-handler 'arg0 #'handle-arg0)
  (register-opcode-handler 'myargcount #'handle-myargcount)
  (register-opcode-handler 'pvarsetpop0 #'handle-pvarsetpop0)
  (register-opcode-handler 'pvarsetpop1 #'handle-pvarsetpop1)
  (register-opcode-handler 'pvarsetpop2 #'handle-pvarsetpop2)
  (register-opcode-handler 'pvarsetpop3 #'handle-pvarsetpop3)
  (register-opcode-handler 'pvarsetpop4 #'handle-pvarsetpop4)
  (register-opcode-handler 'pvarsetpop5 #'handle-pvarsetpop5)
  (register-opcode-handler 'pvarsetpop6 #'handle-pvarsetpop6)

  ;; Control flow
  (register-opcode-handler 'return #'handle-return)
  (register-opcode-handler 'jump #'handle-jump)
  (register-opcode-handler 'jumpif #'handle-jumpif)
  (register-opcode-handler 'jumpifnil #'handle-jumpifnil)
  (register-opcode-handler 'jump0 #'handle-jump0)
  (register-opcode-handler 'jump1 #'handle-jump1)
  (register-opcode-handler 'jump2 #'handle-jump2)
  (register-opcode-handler 'jump3 #'handle-jump3)
  (register-opcode-handler 'jump4 #'handle-jump4)
  (register-opcode-handler 'jump5 #'handle-jump5)
  (register-opcode-handler 'jump6 #'handle-jump6)
  (register-opcode-handler 'jump7 #'handle-jump7)
  (register-opcode-handler 'jump8 #'handle-jump8)
  (register-opcode-handler 'jump9 #'handle-jump9)
  (register-opcode-handler 'jump10 #'handle-jump10)
  (register-opcode-handler 'jump11 #'handle-jump11)
  (register-opcode-handler 'jump12 #'handle-jump12)
  (register-opcode-handler 'jump13 #'handle-jump13)
  (register-opcode-handler 'jump14 #'handle-jump14)
  (register-opcode-handler 'jump15 #'handle-jump15)
  (register-opcode-handler 'fjump0 #'handle-fjump0)
  (register-opcode-handler 'fjump1 #'handle-fjump1)
  (register-opcode-handler 'fjump2 #'handle-fjump2)
  (register-opcode-handler 'fjump3 #'handle-fjump3)
  (register-opcode-handler 'fjump4 #'handle-fjump4)
  (register-opcode-handler 'fjump5 #'handle-fjump5)
  (register-opcode-handler 'fjump6 #'handle-fjump6)
  (register-opcode-handler 'fjump7 #'handle-fjump7)
  (register-opcode-handler 'fjump8 #'handle-fjump8)
  (register-opcode-handler 'fjump9 #'handle-fjump9)
  (register-opcode-handler 'fjump10 #'handle-fjump10)
  (register-opcode-handler 'fjump11 #'handle-fjump11)
  (register-opcode-handler 'fjump12 #'handle-fjump12)
  (register-opcode-handler 'fjump13 #'handle-fjump13)
  (register-opcode-handler 'fjump14 #'handle-fjump14)
  (register-opcode-handler 'fjump15 #'handle-fjump15)
  (register-opcode-handler 'tjump0 #'handle-tjump0)
  (register-opcode-handler 'tjump1 #'handle-tjump1)
  (register-opcode-handler 'tjump2 #'handle-tjump2)
  (register-opcode-handler 'tjump3 #'handle-tjump3)
  (register-opcode-handler 'tjump4 #'handle-tjump4)
  (register-opcode-handler 'tjump5 #'handle-tjump5)
  (register-opcode-handler 'tjump6 #'handle-tjump6)
  (register-opcode-handler 'tjump7 #'handle-tjump7)
  (register-opcode-handler 'tjump8 #'handle-tjump8)
  (register-opcode-handler 'tjump9 #'handle-tjump9)
  (register-opcode-handler 'tjump10 #'handle-tjump10)
  (register-opcode-handler 'tjump11 #'handle-tjump11)
  (register-opcode-handler 'tjump12 #'handle-tjump12)
  (register-opcode-handler 'tjump13 #'handle-tjump13)
  (register-opcode-handler 'tjump14 #'handle-tjump14)
  (register-opcode-handler 'tjump15 #'handle-tjump15)
  (register-opcode-handler 'jumpx #'handle-jumpx)
  (register-opcode-handler 'fjumpx #'handle-fjumpx)
  (register-opcode-handler 'tjumpx #'handle-tjumpx)
  (register-opcode-handler 'fn0 #'handle-fn0)
  (register-opcode-handler 'fn1 #'handle-fn1)
  (register-opcode-handler 'fn2 #'handle-fn2)
  (register-opcode-handler 'fn3 #'handle-fn3)
  (register-opcode-handler 'fn4 #'handle-fn4)
  (register-opcode-handler 'fnx #'handle-fnx)
  (register-opcode-handler 'applyfn #'handle-applyfn)

  ;; Memory operations
  (register-opcode-handler 'aref1 #'handle-aref1)
  (register-opcode-handler 'aset1 #'handle-aset1)
  (register-opcode-handler 'aref2 #'handle-aref2)
  (register-opcode-handler 'aset2 #'handle-aset2)
  (register-opcode-handler 'getael1 #'handle-getael1)
  (register-opcode-handler 'getael2 #'handle-getael2)
  (register-opcode-handler 'setael1 #'handle-setael1)
  (register-opcode-handler 'setael2 #'handle-setael2)
  (register-opcode-handler 'getbasebyte #'handle-getbasebyte)
  (register-opcode-handler 'putbasebyte #'handle-putbasebyte)
  (register-opcode-handler 'getbase-n #'handle-getbase-n)
  (register-opcode-handler 'getbaseptr-n #'handle-getbaseptr-n)
  (register-opcode-handler 'putbase-n #'handle-putbase-n)
  (register-opcode-handler 'putbaseptr-n #'handle-putbaseptr-n)
  (register-opcode-handler 'addbase #'handle-addbase)

  ;; Bitwise operations
  (register-opcode-handler 'logand #'handle-logand)
  (register-opcode-handler 'logior #'handle-logior)
  (register-opcode-handler 'logxor #'handle-logxor)
  (register-opcode-handler 'lognot #'handle-lognot)
  (register-opcode-handler 'lsh #'handle-lsh)
  (register-opcode-handler 'llsh1 #'handle-llsh1)
  (register-opcode-handler 'llsh8 #'handle-llsh8)
  (register-opcode-handler 'lrsh1 #'handle-lrsh1)
  (register-opcode-handler 'lrsh8 #'handle-lrsh8)
  (register-opcode-handler 'logor2 #'handle-logor2)
  (register-opcode-handler 'logand2 #'handle-logand2)
  (register-opcode-handler 'logxor2 #'handle-logxor2)
  (register-opcode-handler 'hiloc #'handle-hiloc)
  (register-opcode-handler 'loloc #'handle-loloc)

  ;; Miscellaneous
  (register-opcode-handler 'bind #'handle-bind)
  (register-opcode-handler 'unbind #'handle-unbind)
  (register-opcode-handler 'dunbind #'handle-dunbind)
  (register-opcode-handler 'typep #'handle-typep)
  (register-opcode-handler 'fixp #'handle-fixp)
  (register-opcode-handler 'smallp #'handle-smallp)
  (register-opcode-handler 'charcode #'handle-charcode)
  (register-opcode-handler 'charn #'handle-charn)
  (register-opcode-handler 'store #'handle-store)
  (register-opcode-handler 'unwind #'handle-unwind)
  (register-opcode-handler 'listget #'handle-listget)
  (register-opcode-handler 'assoc #'handle-assoc)
  (register-opcode-handler 'fmemb #'handle-fmemb)
  (register-opcode-handler 'stkscan #'handle-stkscan)
  (register-opcode-handler 'pop-n #'handle-pop-n)
  (register-opcode-handler 'gcref #'handle-gcref)
  (register-opcode-handler 'aconst #'handle-aconst)
  (register-opcode-handler 'sic #'handle-sic)
  (register-opcode-handler 'snic #'handle-snic)
  (register-opcode-handler 'sicx #'handle-sicx)
  (register-opcode-handler 'gconst #'handle-gconst)
  (register-opcode-handler 'makenumber #'handle-makenumber)
  (register-opcode-handler 'cl-equal #'handle-cl-equal)
  (register-opcode-handler 'swap #'handle-swap)
  (register-opcode-handler 'nop #'handle-nop)

   ;; Arithmetic (general)
   (register-opcode-handler 'plus2 #'handle-plus2)
   (register-opcode-handler 'difference #'handle-difference)
   (register-opcode-handler 'times2 #'handle-times2)
   (register-opcode-handler 'quotient #'handle-quotient)

   ;; Graphics operations
   (register-opcode-handler 'bitblt #'handle-bitblt)
   (register-opcode-handler 'drawline #'handle-drawline)

   ;; UFN and subroutine calls
   (register-opcode-handler 'ufn #'handle-ufn)
   (register-opcode-handler 'subrcall #'handle-subrcall)

   ;; Context switching
   (register-opcode-handler 'contextsw #'handle-contextsw))

;; Dispatch an opcode
(defun dispatch-opcode (vm opcode &optional operands)
  "Dispatch an opcode to its handler"
   (let ((handler (get-opcode-handler opcode)))
     (if handler
         (funcall handler vm operands)
         (error 'maiko-lisp.utils:vm-error
                :message (format nil "Unknown opcode: ~A" opcode)))))

;; Note: initialize-opcode-handlers is called in main.lisp after all handler files are loaded
