(require :asdf)
(load "src/package.lisp")
(load "src/utils/types.lisp")
(load "src/utils/errors.lisp")
(load "src/data/cons-defs.lisp")
(load "src/memory/storage.lisp")
(load "src/data/cons.lisp")
(load "src/data/array.lisp")
(load "src/data/function-header.lisp")
(load "src/data/sysout-utils.lisp")
(load "src/data/bytecode.lisp")
(load "src/data/frame-extension.lisp")
(load "src/data/atom.lisp")
(load "src/data/defcell.lisp")
(load "src/data/sysout.lisp")
(load "src/memory/gc.lisp")
(load "src/memory/virtual.lisp")
(load "src/memory/layout.lisp")
(load "src/utils/address.lisp")
(load "src/vm/stack.lisp")
(load "src/vm/interrupt.lisp")
(load "src/vm/trace.lisp")
(load "src/vm/op-macros.lisp")
(load "src/vm/dispatch.lisp")
(load "src/vm/op-stack.lisp")
(load "src/vm/op-arithmetic.lisp")
(load "src/vm/op-list.lisp")
(load "src/vm/op-comparison.lisp")
(load "src/vm/op-variable.lisp")
(load "src/vm/op-control.lisp")
(load "src/vm/op-memory.lisp")
(load "src/vm/op-logic.lisp")
(load "src/vm/op-const.lisp")
(load "src/vm/op-misc.lisp")
(load "src/vm/op-graphics.lisp")
(load "src/vm/opcodes-main.lisp")
(load "src/vm/function.lisp")
(load "src/main.lisp")

;; When running as script, *posix-argv* is (sbcl loader.lisp arg1 arg2 ...)
;; We want to pass (arg1 arg2 ...) to main
(let ((args (cdr sb-ext:*posix-argv*)))
  ;; Remove the script name (loader.lisp) if present
  (when (and args (string= (file-namestring (first args)) "loader.lisp"))
    (setf args (rest args)))
  
  (handler-bind ((error (lambda (c)
                          (format t "Error: ~A~%" c)
                          (sb-debug:print-backtrace)
                          (sb-ext:exit :code 1))))
    (laiko:main args)))
(sb-ext:exit :code 0)
