(in-package :laiko-tests)

(defun test-bind-debug2 ()
  "Debug BIND operation with more detail"
  (format t "~%Debugging BIND operation (detailed)...~%")
  (let ((vm (laiko.vm:create-vm #x400)))
    (setf (laiko.vm::vm-pvar-ptr vm) 10)
    (format t "pvar-ptr before bind: ~A~%" (laiko.vm::vm-pvar-ptr vm))
    (laiko.vm:push-stack vm 42)
    (format t "stack-ptr after push: ~A~%" (laiko.vm:vm-stack-ptr vm))
    (format t "stack[0]: ~A~%" (aref (laiko.vm:vm-stack vm) 0))
    (let* ((operand #x11)
           (n1 (ash operand -4))
           (n2 (logand operand #xF))
           (total (+ n1 n2)))
      (format t "Operand ~X: n1=~A n2=~A total=~A~%" operand n1 n2 total)
      (let ((old-ptr (laiko.vm::vm-pvar-ptr vm)))
        (format t "old pvar-ptr: ~A~%" old-ptr)
        (setf (laiko.vm::vm-pvar-ptr vm) (+ old-ptr total))
        (format t "new pvar-ptr: ~A~%" (laiko.vm::vm-pvar-ptr vm))
        (format t "Binding n1=~A to NIL~%" n1)
        (loop for i from 0 below n1 do
          (let ((slot-addr (+ old-ptr i)))
            (format t "Set PVAR~A (offset ~A) to 0~%" i slot-addr)
            (laiko.vm:set-pvar-slot vm i 0)))
        (let ((stack-ptr (laiko.vm:vm-stack-ptr vm))
              (stack (laiko.vm:vm-stack vm)))
          (format t "Binding n2=~A from stack~%" n2)
          (loop for i from 0 below n2 do
            (let ((value (aref stack (- stack-ptr 1 i))))
              (format t "i=~A: stack[~A]=~A~%" i (- stack-ptr 1 i) value)
              (let ((slot-addr (+ old-ptr n1 i)))
                (format t "Set PVAR~A (offset ~A) to ~A~%" (+ n1 i) slot-addr value)
                (laiko.vm:set-pvar-slot vm (+ n1 i) value)))))))
    (format t "~%Results:~%")
    (loop for i from 0 below 4 do
      (format t "PVAR~A: ~A~%" i (laiko.vm:get-pvar-slot vm i)))))

(test-bind-debug2)
